ItemCDBMigrations/Controllers/ActualPController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ItemCDBMigrations.Models;
using PagedList;

namespace ItemCDBMigrations.Controllers
{
    [Authorize(Roles = "RSG.DBH_ItemCtlAdmin, RSG.DBH_ItemCtlDBA")]
    public class ActualPController : Controller
    {
        private ICContext db = new ICContext();

        // GET: ActualP
        public ActionResult Index(string searchString, string sortOrder, string currentFilter, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.EmplType = string.IsNullOrEmpty(sortOrder) ? "empltype_desc" : "";
            ViewBag.EffectiveDate = sortOrder == "efdate" ? "efdate_desc" : "efdate";

            if (searchString != null)
                page = 1;
            else
                searchString = currentFilter;

            ViewBag.CurrentFilter = searchString;

            var tblPOSITIONACTUALs = db.tblPOSITIONACTUALs.Include(t => t.tblEMPLOYEELIST).Include(t => t.tblEmploymentType).
                Include(t => t.tblPayPeriod).Include(t => t.tblPOSITIONBUDGETED).Include(t => t.tblStep);

            if(!string.IsNullOrEmpty(searchString))
            {
                // search by employee
                //tblPOSITIONACTUALs = tblPOSITIONACTUALs.Where(t => t.tblEMPLOYEELIST.LastName.Contains(searchString) || t.tblEMPLOYEELIST.FirstName.Contains(searchString));

                // search by item name or employee name
                tblPOSITIONACTUALs = tblPOSITIONACTUALs.Where(t => t.tblPOSITIONBUDGETED.tblBudItemNum.BudItemDesc.Contains(searchString)
                                                                || t.tblPOSITIONBUDGETED.BudItemNum.Contains(searchString)
                                                                || t.tblEMPLOYEELIST.LastName.Contains(searchString)
                                                                || t.tblEMPLOYEELIST.FirstName.Contains(searchString));
            }

            switch(sortOrder)
            {
                case "empltype_desc":
                    tblPOSITIONACTUALs = tblPOSITIONACTUALs.OrderByDescending(t => t.EmplType);
                    break;

                case "efdate":
                    tblPOSITIONACTUALs = tblPOSITIONACTUALs.OrderBy(t => t.EffectiveDate);
                    break;

                case "efdate_desc":
                    tblPOSITIONACTUALs = tblPOSITIONACTUALs.OrderByDescending(t => t.EffectiveDate);
                    break;

                default:
                    tblPOSITIONACTUALs = tblPOSITIONACTUALs.OrderBy(t => t.EmplType);
                    break;
            }

            int pageNumber = page ?? 1;
            int pageSize = 10;

            return View(tblPOSITIONACTUALs.ToPagedList(pageNumber, pageSize));
        }

        // GET: ActualP/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblPOSITIONACTUAL tblPOSITIONACTUAL = db.tblPOSITIONACTUALs.Find(id);
            if (tblPOSITIONACTUAL == null)
            {
                return HttpNotFound();
            }
            var items = from x in db.tblBudItemNums
                        let itemInfo = x.BudItemNum + " - " + x.BudItemDesc
                        orderby x.BudItemNum
                        select new { x.BudItemNum, itemInfo };
            ViewBag.ActItemNum = items.FirstOrDefault(x => tblPOSITIONACTUAL.ActItemNum == x.BudItemNum).itemInfo;
            ViewBag.PreItemNum = tblPOSITIONACTUAL.PreItemNum != null ? items.FirstOrDefault(x => tblPOSITIONACTUAL.PreItemNum == x.BudItemNum).itemInfo : "";
            return View(tblPOSITIONACTUAL);
        }

        private ActionResult FillFields(tblPOSITIONACTUAL defaultValues)
        {            
            var employees = from x in db.tblEMPLOYEELISTs
                            let myEmplID = x.EmplID + " - " + x.LastName + ", " + x.FirstName
                            where x.EmplStatus == "A"
                            select new { x.EmplID, myEmplID };

            ViewBag.EmplID = new SelectList(employees, "EmplID", "myEmplID");
            ViewBag.ActEmplStatus = new SelectList(db.tblEmplStatus, "EmplStatusCode", "EmplStatusDesc");
            ViewBag.EmplType = new SelectList(db.tblEmploymentTypes, "EmplType", "EmplTypeDesc");
            ViewBag.PayPeriod = new SelectList(db.tblPayPeriods, "PayTypeID", "PayTypeDesc");

            var budpos = from x in db.tblPOSITIONBUDGETEDs
                         where x.BudFilled == 0
                         select new { x.BudPosNum };
            ViewBag.ActPosNum = new SelectList(budpos, "BudPosNum", "BudPosNum");
            ViewBag.Step = new SelectList(db.tblSteps, "Step", "Step");

            var items = from x in db.tblBudItemNums
                        let itemInfo = x.BudItemNum + " - " + x.BudItemDesc
                        orderby x.BudItemNum
                        select new { x.BudItemNum, itemInfo };
            ViewBag.ActItemNum = new SelectList(items, "BudItemNum", "itemInfo");
            ViewBag.PreItemNum = new SelectList(items, "BudItemNum", "itemInfo");

            var subitems = from x in db.tblSubItems
                           let subinfo = x.SubItemCode + " - " + x.SubItemDesc
                           orderby x.SubItemCode
                           select new { x.SubItemCode, subinfo };
            ViewBag.ActSubItem = new SelectList(subitems, "SubItemCode", "subinfo");
            ViewBag.PreSubItem = new SelectList(subitems, "SubItemCode", "subinfo");
            return View(defaultValues);
        }

        // GET: ActualP/Create
        public ActionResult Create()
        {
            tblPOSITIONACTUAL defaultValues = new tblPOSITIONACTUAL();
            defaultValues.ActEmplStatus = "A";
            defaultValues.EffectiveDate = DateTime.Now;
            return FillFields(defaultValues);
        }

        // POST: ActualP/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ActPosAutoID,ActPosNum,EmplID,EffectiveDate,DeptHireDate,ActEmplStatus,ActItemNum,ActSubItem,Step,PayRate,PayPeriod,EmplType,PreItemNum,PreSubItem,ReasonOfChange,Comments")] tblPOSITIONACTUAL tblPOSITIONACTUAL)        
        {
            if (ModelState.IsValid)
            {
                db.tblPOSITIONACTUALs.Add(tblPOSITIONACTUAL);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return FillFields(tblPOSITIONACTUAL);
        }

        private ActionResult FillFieldsEdit(tblPOSITIONACTUAL tblPOSITIONACTUAL)
        {
            var employees = from x in db.tblEMPLOYEELISTs
                            let myEmplID = x.EmplID + " - " + x.LastName + ", " + x.FirstName
                            select new { x.EmplID, myEmplID };

            ViewBag.EmplID = new SelectList(employees, "EmplID", "myEmplID", tblPOSITIONACTUAL.EmplID);
            ViewBag.ActEmplStatus = new SelectList(db.tblEmplStatus, "EmplStatusCode", "EmplStatusDesc", tblPOSITIONACTUAL.ActEmplStatus);
            ViewBag.EmplType = new SelectList(db.tblEmploymentTypes, "EmplType", "EmplTypeDesc", tblPOSITIONACTUAL.EmplType);
            ViewBag.PayPeriod = new SelectList(db.tblPayPeriods, "PayTypeID", "PayTypeDesc", tblPOSITIONACTUAL.PayPeriod);

            var budpos = from x in db.tblPOSITIONBUDGETEDs
                         select new { x.BudPosNum };
            ViewBag.ActPosNum = new SelectList(budpos, "BudPosNum", "BudPosNum", tblPOSITIONACTUAL.ActPosNum);
            ViewBag.Step = new SelectList(db.tblSteps, "Step", "Step", tblPOSITIONACTUAL.Step);

            var items = from x in db.tblBudItemNums
                        let itemInfo = x.BudItemNum + " - " + x.BudItemDesc
                        orderby x.BudItemNum
                        select new { x.BudItemNum, itemInfo };
            ViewBag.ActItemNum = new SelectList(items, "BudItemNum", "itemInfo", tblPOSITIONACTUAL.ActItemNum);
            ViewBag.PreItemNum = new SelectList(items, "BudItemNum", "itemInfo", tblPOSITIONACTUAL.PreItemNum);

            var subitems = from x in db.tblSubItems
                           let subinfo = x.SubItemCode + " - " + x.SubItemDesc
                           orderby x.SubItemCode
                           select new { x.SubItemCode, subinfo };
            ViewBag.ActSubItem = new SelectList(subitems, "SubItemCode", "subinfo", tblPOSITIONACTUAL.ActSubItem);
            ViewBag.PreSubItem = new SelectList(subitems, "SubItemCode", "subinfo", tblPOSITIONACTUAL.PreSubItem);
            return View(tblPOSITIONACTUAL);
        }

        // GET: ActualP/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblPOSITIONACTUAL tblPOSITIONACTUAL = db.tblPOSITIONACTUALs.Find(id);
            if (tblPOSITIONACTUAL == null)
            {
                return HttpNotFound();
            }
            return FillFieldsEdit(tblPOSITIONACTUAL);
        }

        // POST: ActualP/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

ItemCDBMigrations/Views/ActualP/Create.cshtml
@model ItemCDBMigrations.Models.tblPOSITIONACTUAL

@{
    ViewBag.Title = "Create";
}

<h2>New Actual Position</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ActEmplStatus)
        <div class="form-group">
            @Html.LabelFor(model => model.tblPOSITIONBUDGETED.BudPosNum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ActPosNum", null, "Select Unfilled Position Number", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ActPosNum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmplID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EmplID", null, "Select Active Employee", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EmplID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EffectiveDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EffectiveDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EffectiveDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DeptHireDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DeptHireDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeptHireDate, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.tblEMPLOYEELIST.EmplStatus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ActEmplStatus)
                @Html.ValidationMessageFor(model => model.ActEmplStatus, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.ActItemNum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ActItemNum", null, "Select Actual Item", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ActItemNum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ActSubItem, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ActSubItem", null, "Select SubItem", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ActSubItem, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Step, "Step", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Step", null, "Select Step", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Step, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PayRate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PayRate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PayRate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tblPayPeriod.PayTypeDesc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PayPeriod", null, "Select Pay Period", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PayPeriod, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tblEmploymentType.EmplTypeDesc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EmplType", null, "Select Employment Type", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EmplType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PreItemNum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PreItemNum", null, "Select PreItem", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PreItemNum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PreSubItem, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PreSubItem", null, "Select Pre SubItem", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PreSubItem, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReasonOfChange, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReasonOfChange, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReasonOfChange, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comments, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comments, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comments, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add Actual Position" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ItemCDBMigrations/Views/ActualP/Delete.cshtml
@model ItemCDBMigrations.Models.tblPOSITIONACTUAL

@{
    ViewBag.Title = "Delete Actual Position";
}

<h2>@ViewBag.Title</h2>

<h3>Are you sure you want to delete this Actual Position?</h3>
<div>
    <h4>@Model.tblPOSITIONBUDGETED.tblBudItemNum.BudItemDesc</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.tblEMPLOYEELIST.LastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.tblEMPLOYEELIST.LastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.tblEMPLOYEELIST.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.tblEMPLOYEELIST.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.tblEmploymentType.EmplTypeDesc)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.tblEmploymentType.EmplTypeDesc)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.tblPayPeriod.PayTypeDesc)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.tblPayPeriod.PayTypeDesc)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.tblPOSITIONBUDGETED.BudItemNum)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.tblPOSITIONBUDGETED.BudItemNum) - @Html.DisplayFor(model => model.tblPOSITIONBUDGETED.tblBudItemNum.BudItemDesc)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.tblStep.Step)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.tblStep.Step)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EffectiveDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EffectiveDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DeptHireDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DeptHireDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ActEmplStatus)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.tblEMPLOYEELIST.tblEmplStatu.EmplStatusDesc)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ActItemNum)
        </dt>
        <dd>
            @ViewBag.ActItemNum
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ActSubItem)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ActSubItem)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PayRate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PayRate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PreItemNum)
        </dt>
        <dd>
            @ViewBag.PreItemNum
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PreSubItem)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PreSubItem)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ReasonOfChange)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ReasonOfChange)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Comments)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Comments)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-success" }) |
            <input type="submit" value="Delete" class="btn btn-danger" />            
        </div>
    }
</div>

ItemCDBMigrations/Views/ActualP/Index.cshtml
@model PagedList.IPagedList<ItemCDBMigrations.Models.tblPOSITIONACTUAL>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" type="text/css" rel="stylesheet" />

@{
    ViewBag.Title = "Index";
}

<h2>Actual Position Search</h2>
<p>
    @Html.ActionLink("Create New Actual Position", "Create")
</p>

@using (Html.BeginForm("Index", "ActualP", FormMethod.Get))
{
    <p> Item or Name: 
        @Html.TextBox("searchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p> 
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model[0].tblEMPLOYEELIST.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].tblEMPLOYEELIST.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].tblPOSITIONBUDGETED.BudItemNum)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].ActItemNum)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].ActSubItem)
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.EffectiveDate)*@
            @Html.ActionLink("Effective Date", "Index", new { currentFilter = ViewBag.CurrentFilter, sortOrder = ViewBag.EffectiveDate })
        </th>
        <th>
            @Html.DisplayName("Budgeted Position Number")
        </th>        
        <th>
            @*@Html.DisplayNameFor(model => model.tblEmploymentType.EmplTypeDesc)*@
            @Html.ActionLink("Employment Type", "Index", new { currentFilter = ViewBag.CurrentFilter, sortOrder = ViewBag.EmplType })
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].tblPayPeriod.PayTypeDesc)
        </th>        
        <th>
            @Html.DisplayNameFor(model => model[0].tblStep.Step)
        </th>        
        <th>
            @Html.DisplayNameFor(model => model[0].DeptHireDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].tblEMPLOYEELIST.tblEmplStatu.EmplStatusDesc)
        </th>        
        <th>
            @Html.DisplayNameFor(model => model[0].PayRate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].PreItemNum)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].PreSubItem)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].ReasonOfChange)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].Comments)
        </th>        
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.tblEMPLOYEELIST.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tblEMPLOYEELIST.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tblPOSITIONBUDGETED.BudItemNum)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ActItemNum)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ActSubItem)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EffectiveDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tblPOSITIONBUDGETED.BudPosNum)
        </td>        
        <td>
            @Html.DisplayFor(modelItem => item.tblEmploymentType.EmplTypeDesc)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tblPayPeriod.PayTypeDesc)
        </td>        
        <td>
            @Html.DisplayFor(modelItem => item.tblStep.Step)
        </td>        
        <td>
            @Html.DisplayFor(modelItem => item.DeptHireDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tblEMPLOYEELIST.tblEmplStatu.EmplStatusDesc)
        </td>        
        <td>
            @Html.DisplayFor(modelItem => item.PayRate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PreItemNum)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PreSubItem)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReasonOfChange)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Comments)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ActPosAutoID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ActPosAutoID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ActPosAutoID })
        </td>
    </tr>
}

</table>

@if(Model != null && Model.TotalItemCount > 0)
{
    <h4>@Model.TotalItemCount Records found</h4>
    if (Model.TotalItemCount > Model.PageSize)
    {
        <div>Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount</div>
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
    }
}