ItemCDBMigrations/Controllers/BudgetedPController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ItemCDBMigrations.Models;
using PagedList;

namespace ItemCDBMigrations.Controllers
{
    [Authorize(Roles = "RSG.DBH_ItemCtlAdmin, RSG.DBH_ItemCtlDBA")]
    public class BudgetedPController : Controller
    {
        private ICContext db = new ICContext();

        // GET: BudgetedP
        public ActionResult Index(string searchString, string sortOrder, string currentFilter, int? page)
        {
            ViewBag.ItemD = (string.IsNullOrEmpty(sortOrder)) ? "item_desc" : "";
            ViewBag.Unit = sortOrder == "unit" ? "unit_desc" : "unit";

            if (searchString != null)
                page = 1;
            else
                searchString = currentFilter;

            ViewBag.CurrentFilter = searchString;
            ViewBag.CurrentSortOrder = sortOrder;

            // get the positions
            var tblPOSITIONBUDGETEDs = db.tblPOSITIONBUDGETEDs.Include(t => t.tblBud).
                Include(t => t.tblBudItemNum).Include(t => t.tblDivision).Include(t => t.tblFilled).
                Include(t => t.tblFunction).Include(t => t.tblOrd).Include(t => t.tblOrgCode).
                Include(t => t.tblSection).Include(t => t.tblSubItem).Include(t => t.tblUnit);

            if(!string.IsNullOrEmpty(searchString))
            {
                tblPOSITIONBUDGETEDs = tblPOSITIONBUDGETEDs.Where(t => t.tblBudItemNum.BudItemDesc.Contains(searchString) || t.BudItemNum.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "item_desc":
                    tblPOSITIONBUDGETEDs = tblPOSITIONBUDGETEDs.OrderByDescending(t => t.tblBudItemNum.BudItemDesc);
                    break;

                case "unit":
                    tblPOSITIONBUDGETEDs = tblPOSITIONBUDGETEDs.OrderBy(t => t.tblUnit.UnitDesc);
                    break;

                case "unit_desc":
                    tblPOSITIONBUDGETEDs = tblPOSITIONBUDGETEDs.OrderByDescending(t => t.tblUnit.UnitDesc);
                    break;

                default:
                    tblPOSITIONBUDGETEDs = tblPOSITIONBUDGETEDs.OrderBy(t => t.tblBudItemNum.BudItemDesc);
                    break;
            }

            int pageNumber = page ?? 1;
            int pageSize = 10;

            return View(tblPOSITIONBUDGETEDs.ToPagedList(pageNumber, pageSize));
        }

        // GET: BudgetedP/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblPOSITIONBUDGETED tblPOSITIONBUDGETED = db.tblPOSITIONBUDGETEDs.Find(id);
            if (tblPOSITIONBUDGETED == null)
            {
                return HttpNotFound();
            }
            return View(tblPOSITIONBUDGETED);
        }

        /// <summary>
        /// Fills the ViewBag with the information neccesary for the foorm fields.
        /// </summary>
        /// <returns></returns>
        private ActionResult PrepareFields()
        {
            ViewBag.BudBud = new SelectList(db.tblBuds, "BudCode", "BudDesc");

            var itemconcat = from x in db.tblBudItemNums
                             let BudItemDesc = x.BudItemNum + " - " + x.BudItemDesc
                             orderby x.BudItemDesc
                             select new { x.BudItemNum, BudItemDesc };
            ViewBag.BudItemNum = new SelectList(itemconcat, "BudItemNum", "BudItemDesc");
            //ViewBag.BudItemNum = new SelectList(db.tblBudItemNums, "BudItemNum", "BudItemDesc");

            var divisions = from x in db.tblDivisions
                            let DivDesc = x.DivDesc1 + " - " + x.DivCode
                            orderby x.DivDesc1
                            select new { x.DivCode, DivDesc };
            ViewBag.BudDivCode = new SelectList(divisions, "DivCode", "DivDesc");
            //ViewBag.BudDivCode = new SelectList(db.tblDivisions, "DivCode", "DivDesc");

            ViewBag.BudFilled = new SelectList(db.tblFilleds, "FilledCode", "FilledDesc");
            ViewBag.BudFunction = new SelectList(db.tblFunctions, "FuncCode", "FuncDesc");
            ViewBag.BudOrd = new SelectList(db.tblOrds, "OrdCode", "OrdDesc");
            ViewBag.BudOrgCode = new SelectList(db.tblOrgCodes, "BudOrgCode", "BudOrgCodeDesc");

            var sections = from x in db.tblSections
                           let SecDesc = x.SecDesc1 + " - " + x.SecCode
                           orderby x.SecDesc1
                           select new { x.SecCode, SecDesc };
            ViewBag.BudSecCode = new SelectList(sections, "SecCode", "SecDesc");
            //ViewBag.BudSecCode = new SelectList(db.tblSections, "SecCode", "SecDesc");

            var subconcat = from x in db.tblSubItems
                            let SubItemDesc = x.SubItemCode + " - " + x.SubItemDesc
                            select new { x.SubItemCode, SubItemDesc };
            ViewBag.BudSubItem = new SelectList(subconcat, "SubItemCode", "SubItemDesc");
            //ViewBag.BudSubItem = new SelectList(db.tblSubItems, "SubItemCode", "SubItemDesc");

            var units = from x in db.tblUnits
                        let UnitDesc = x.UnitDesc + " - " + x.UnitCode
                        orderby x.UnitDesc
                        select new { x.UnitCode, UnitDesc };
            ViewBag.BudUnitCode = new SelectList(units, "UnitCode", "UnitDesc");
            //ViewBag.BudUnitCode = new SelectList(db.tblUnits, "UnitCode", "UnitDesc");
            return View();
        }

        // GET: BudgetedP/Create
        public ActionResult Create()
        {
            return PrepareFields();
        }

        // POST: BudgetedP/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BudPosNum,BudItemNum,BudSubItem,BudOrd,BudBud,BudFilled,BudFunction,BudOrgCode,BudDivCode,BudSecCode,BudUnitCode,Comments")] tblPOSITIONBUDGETED tblPOSITIONBUDGETED)
        {
            if (ModelState.IsValid)
            {
                db.tblPOSITIONBUDGETEDs.Add(tblPOSITIONBUDGETED);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            // else, stay on page
            return PrepareFields();
        }

        private ActionResult PrepareEditFields(tblPOSITIONBUDGETED tblPOSITIONBUDGETED)
        {
            ViewBag.BudBud = new SelectList(db.tblBuds, "BudCode", "BudDesc", tblPOSITIONBUDGETED.BudBud);

            var itemconcat = from x in db.tblBudItemNums
                             let BudItemDesc = x.BudItemNum + " - " + x.BudItemDesc
                             orderby x.BudItemDesc
                             select new { x.BudItemNum, BudItemDesc };
            ViewBag.BudItemNum = new SelectList(itemconcat, "BudItemNum", "BudItemDesc", tblPOSITIONBUDGETED.BudItemNum);

            var divisions = from x in db.tblDivisions
                            let DivDesc = x.DivDesc1 + " - " + x.DivCode
                            orderby x.DivDesc1
                            select new { x.DivCode, DivDesc };
            ViewBag.BudDivCode = new SelectList(divisions, "DivCode", "DivDesc", tblPOSITIONBUDGETED.BudDivCode);
            ViewBag.BudFilled = new SelectList(db.tblFilleds, "FilledCode", "FilledDesc", tblPOSITIONBUDGETED.BudFilled);
            ViewBag.BudFunction = new SelectList(db.tblFunctions, "FuncCode", "FuncDesc", tblPOSITIONBUDGETED.BudFunction);
            ViewBag.BudOrd = new SelectList(db.tblOrds, "OrdCode", "OrdDesc", tblPOSITIONBUDGETED.BudOrd);
            ViewBag.BudOrgCode = new SelectList(db.tblOrgCodes, "BudOrgCode", "BudOrgCodeDesc", tblPOSITIONBUDGETED.BudOrgCode);

            var sections = from x in db.tblSections
                           let SecDesc = x.SecDesc1 + " - " + x.SecCode
                           orderby x.SecDesc1
                           select new { x.SecCode, SecDesc };
            ViewBag.BudSecCode = new SelectList(sections, "SecCode", "SecDesc", tblPOSITIONBUDGETED.BudSecCode);

            // create a custom select to concat code and desc in the dropdown list
            var alias = (from x in db.tblSubItems
                         let SubItemDesc = x.SubItemCode + " - " + x.SubItemDesc
                         select new { x.SubItemCode, SubItemDesc });
            ViewBag.BudSubItem = new SelectList(alias, "SubItemCode", "SubItemDesc", tblPOSITIONBUDGETED.BudSubItem);

            var units = from x in db.tblUnits
                        let UnitDesc = x.UnitDesc + " - " + x.UnitCode
                        orderby x.UnitDesc
                        select new { x.UnitCode, UnitDesc };
            ViewBag.BudUnitCode = new SelectList(units, "UnitCode", "UnitDesc", tblPOSITIONBUDGETED.BudUnitCode);
            return View(tblPOSITIONBUDGETED);
        }

        // GET: BudgetedP/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblPOSITIONBUDGETED tblPOSITIONBUDGETED = db.tblPOSITIONBUDGETEDs.Find(id);
            if (tblPOSITIONBUDGETED == null)
            {
                return HttpNotFound();
            }
            // otherwise, fill the fields with current values
            return PrepareEditFields(tblPOSITIONBUDGETED);
        }

        // POST: BudgetedP/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.

ItemCDBMigrations/Views/BudgetedP/Create.cshtml
@model ItemCDBMigrations.Models.tblPOSITIONBUDGETED

@{
    ViewBag.Title = "New Budgeted Position";
}

<h2>New Budgeted Position</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.BudPosNum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BudPosNum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BudPosNum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Item", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BudItemNum", null, "Select Item", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BudItemNum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BudSubItem, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BudSubItem", null, "Select Sub-Item", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BudSubItem, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tblOrd.OrdDesc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BudOrd", null, "Select Ordinance", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BudOrd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tblBud.BudDesc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BudBud", null, "Select Budget", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BudBud, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tblFilled.FilledDesc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BudFilled", null, "Select Filled", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BudFilled, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tblFunction.FuncDesc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BudFunction", null, "Select Function", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BudFunction, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tblOrgCode.BudOrgCodeDesc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BudOrgCode", null, "Select Org Code", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BudOrgCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tblDivision.DivDesc1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BudDivCode", null, "Select Division", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BudDivCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tblSection.SecDesc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BudSecCode", null, "Select Section", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BudSecCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tblUnit.UnitDesc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BudUnitCode", null, "Select Unit", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BudUnitCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comments, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comments, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comments, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add Budgeted Position" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ItemCDBMigrations/Views/BudgetedP/Delete.cshtml
@model ItemCDBMigrations.Models.tblPOSITIONBUDGETED

@{
    ViewBag.Title = "Delete Budgeted Position";
}

<h2>@ViewBag.Title</h2>

<h3>Are you sure you want to delete this Budgeted Position?</h3>
<div>
    <h4>@Model.tblBudItemNum.BudItemDesc</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.tblBud.BudDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblBud.BudDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblBudItemNum.BudItemDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblBudItemNum.BudItemDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblDivision.DivDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblDivision.DivDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblFilled.FilledDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblFilled.FilledDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblFunction.FuncDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblFunction.FuncDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblOrd.OrdDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblOrd.OrdDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblOrgCode.BudOrgCodeDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblOrgCode.BudOrgCodeDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblSection.SecDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblSection.SecDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblSubItem.SubItemDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblSubItem.SubItemDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblUnit.UnitDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblUnit.UnitDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comments)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comments)
        </dd>
        
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-success " }) |
            <input type="submit" value="Delete" class="btn btn-danger" />            
        </div>
    }
</div>

ItemCDBMigrations/Views/BudgetedP/Details.cshtml
@model ItemCDBMigrations.Models.tblPOSITIONBUDGETED

@{
    ViewBag.Title = "Details Budgeted Position";
}

<h2>Budgeted Position Details</h2>

<div>
    <h4>@Model.tblBudItemNum.BudItemDesc</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Budgeted Position Number")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BudPosNum)
        </dd>
        <dt>
            @Html.DisplayName("Item Number")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BudItemNum)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.tblBudItemNum.BudItemDesc)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.tblBudItemNum.BudItemDesc)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.tblBud.BudDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblBud.BudDesc)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.tblDivision.DivDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblDivision.DivDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblFilled.FilledDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblFilled.FilledDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblFunction.FuncDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblFunction.FuncDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblOrd.OrdDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblOrd.OrdDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblOrgCode.BudOrgCodeDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblOrgCode.BudOrgCodeDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblSection.SecDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblSection.SecDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblSubItem.SubItemDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BudSubItem) - @Html.DisplayFor(model => model.tblSubItem.SubItemDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblUnit.UnitDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblUnit.UnitDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comments)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comments)
        </dd>        
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.BudPosNum }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ItemCDBMigrations/Views/BudgetedP/Index.cshtml
@model PagedList.IPagedList<ItemCDBMigrations.Models.tblPOSITIONBUDGETED>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Budgeted Positions";
}

<h2>Budgeted Position Search</h2>

<p>
    @Html.ActionLink("Create New Budgeted Position", "Create")
</p>
@using (Html.BeginForm("Index", "BudgetedP", FormMethod.Get))
{
    <p>Item: @Html.TextBox("searchString", ViewBag.CurrentFilter as string) 
    <input type="submit" value="Search" /></p>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Budgeted Position Number")
        </th>
        <th>
            @Html.DisplayName("Item Number")            
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.tblBudItemNum.BudItemDesc)*@
            @Html.ActionLink("Item Description", "Index", new { currentFilter = ViewBag.CurrentFilter, sortOrder = ViewBag.ItemD })
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].tblBud.BudDesc)
        </th>        
        <th>
            @Html.DisplayNameFor(model => model[0].tblDivision.DivDesc)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].tblFilled.FilledDesc)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].tblFunction.FuncDesc)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].tblOrd.OrdDesc)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].tblOrgCode.BudOrgCodeDesc)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].tblSection.SecDesc)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].tblSubItem.SubItemDesc)
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.tblUnit.UnitDesc)*@
            @Html.ActionLink("Unit", "Index", new { currentFilter = ViewBag.CurrentFilter, sortOrder = ViewBag.Unit })
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].Comments)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.BudPosNum)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BudItemNum)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tblBudItemNum.BudItemDesc)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tblBud.BudDesc)
        </td>        
        <td>
            @Html.DisplayFor(modelItem => item.tblDivision.DivDesc)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tblFilled.FilledDesc)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tblFunction.FuncDesc)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tblOrd.OrdDesc)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tblOrgCode.BudOrgCodeDesc)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tblSection.SecDesc)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tblSubItem.SubItemDesc)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tblUnit.UnitDesc)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Comments)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.BudPosNum }) |
            @Html.ActionLink("Details", "Details", new { id=item.BudPosNum }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.BudPosNum })
        </td>
    </tr>
}

</table>
<h4>@(Model.TotalItemCount > 0 ? Model.TotalItemCount + " Records found" : "")</h4>
@if(Model.TotalItemCount > Model.PageSize)
{
    <div>Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount</div>
    @Html.PagedListPager(Model, pg => Url.Action("Index", new { page = pg, sortOrder = ViewBag.CurrentSortOrder, currentFilter = ViewBag.CurrentFilter }))
}